---
title: "Aphid Collection Tower Site at KBS"
author: "Matthew J Watts"
date: "21 May 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###Load the following packages (and install if required)

```{r}
#install.packages("tidyverse")
#install.packages("readr")
#install.packages("plyr")
#install.packages("scales")
library(tidyverse)
library(readr)
library(plyr)
library(scales)

```


```{r}
VecDyn_template <-data.frame(title = character(),
                             taxon = character(),
                             sample_start_date = as.Date(character()),
                             sample_start_time = character(),
                             sample_end_date = as.Date(character()),
                             sample_end_time = character(),
                             value = numeric(),
                             sample_location_info = character(),
                             sample_info = character(),
                             sample_name = character(),
                             sample_sex = character(),
                             location_description = character(),
                             location_environment =character(),
                             study_lat_DD = double(),
                             study_long_DD = double(),
                             spatial_accuracy = numeric(),
                             location_extent = character(),
                             geo_datum = character(),
                             species_id_method = character(),
                             study_design = character(),
                             sampling_strategy = character(),
                             sampling_method = character(),
                             sampling_protocol = character(),
                             measurement_unit = character(),
                             study_collection_area = character(),
                             value_transform = character(),
                             stringsAsFactors=FALSE)
#write.csv(VecDyn_template, file = "VecDyn_template.csv", row.names = FALSE)
                             
```

```{r}
aphid_Collection <- read.csv(url("https://lter.kbs.msu.edu/datatables/122.csv"))
```


headers = read.csv(file, skip = 1, header = F, nrows = 1, as.is = T)
df = read.csv(file, skip = 3, header = F)
colnames(df)= headers


```{r}
aphid_headers <- read_csv("C:/Users/matt/OneDrive - Imperial College London/ScienceWork/Imperial/VectorBite/VecDynDocumentation/DataSets/AphidCollectionTowerSiteatKBS/122-aphid+colonization+via+suction+traps_clean.csv", skip = 23, header = F, nrows = 1, as.is = T)


```
      

```{r}
Rhopalosiphum_padi <- dplyr::filter(aphid_all, species == "Rhopalosiphum.padi", state == "IL")
```

```{r}
head(Rhopalosiphum_padi)
```

```{r}

r.padi_vecdyn <- VecDyn_template
taxon <- Rhopalosiphum_padi$species
sample_end_date <- Rhopalosiphum_padi$sample_date
location_description <- Rhopalosiphum_padi$state
sample_location_info <- Rhopalosiphum_padi$station
sample_sex <- Rhopalosiphum_padi$sex
value <- Rhopalosiphum_padi$count

a <- cbind(taxon, sample_end_date,location_description,sample_location_info,sample_info,value)
a <- data.frame(a)

r.padi_vecdyn <- rbind.fill(r.padi_vecdyn,a)

r.padi_vecdyn <- 
  r.padi_vecdyn %>%
  dplyr::mutate(title = 'Aphid Collection Tower Site at KBS, Rhopalosiphum.padi, illinois') %>%
  dplyr::mutate(sampling_method = 'Suction Traps') %>%
  dplyr::mutate(measurement_unit = 'individuals') %>%
  dplyr::mutate(location_description = 'Illinois, United States') %>%
  dplyr::mutate(sample_end_date = as.Date(sample_end_date, format = "%d/%m/%Y"))


```


```{r}

head(r.padi_vecdyn)

```

```{r}


write_csv(r.padi_vecdyn,"r.padi_vecdyn.csv", na = "")


```