site_name: VectorBite Data Platform
docs_dir: static/docs
site_dir: static/site
theme: readthedocs
nav:
    - Home: index.md
    - Release Notes: release_notes.md
    - VecTraits:
        - VecTraits Home: vectraits/index.md
        - How to Download: vectraits/downloading.md
        - Field Definitions: vectraits/field_definition_overview.md
    - VecDyn:
        - VecDyn Home: vecdyn/index.md
        - The Database: vecdyn/database.md
        - Field Definitions: vecdyn/field_definitions.md
        - Download Data: vecdyn/downloading.md
        - Submit Data: vecdyn/submitting.md
        - Curation: vecdyn/curation.md
        - Tutorials: vecdyn/tutorials.md
        - Miscellaneous: vecdyn/miscellaneous.md

